# Generated by Django 4.0.3 on 2022-04-18 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slg', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=256)),
                ('body', models.TextField()),
                ('image', models.ImageField(default='', null=True, upload_to='blogs')),
                ('active', models.BooleanField(default=False)),
                ('created_At', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
